# Generated by Django 3.2.18 on 2023-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0009_auto_20230516_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprocessasync',
            name='post_processing_object',
        ),
        migrations.AddField(
            model_name='postprocessasync',
            name='result_post_processing',
            field=models.JSONField(blank=True, default=dict, verbose_name='Result Post Processing'),
        ),
        migrations.AlterField(
            model_name='postprocessing',
            name='output_files',
            field=models.ManyToManyField(blank=True, related_name='post_processing_output_files', to='osis_document.Upload', verbose_name='Output'),
        ),
    ]
