# Generated by Django 3.2.18 on 2023-05-30 11:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0010_auto_20230516_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprocessasync',
            name='data_post_processing',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Data Post Processing'),
        ),
        migrations.AlterField(
            model_name='postprocessasync',
            name='result_post_processing',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Result Post Processing'),
        ),
    ]
