# Generated by Django 3.2.18 on 2023-06-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0012_postprocessasync_async_post_processing_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postprocessasync',
            old_name='data_post_processing',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='postprocessasync',
            old_name='result_post_processing',
            new_name='results',
        ),
        migrations.RemoveField(
            model_name='postprocessasync',
            name='async_post_processing_progress',
        ),
    ]
