# Generated by Django 2.2.24 on 2022-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=255, upload_to='', verbose_name='File'),
        ),
    ]
