# Generated by Django 3.2.12 on 2022-08-03 16:01

from django.db import migrations

from osis_document.utils import calculate_hash


def forward(apps, schema_editor):
    Upload = apps.get_model('osis_document', 'Upload')
    for upload in Upload.objects.all():
        upload.metadata.pop('md5')
        with upload.file.open() as f:
            upload.metadata['hash'] = calculate_hash(f)
        upload.save()


class Migration(migrations.Migration):
    dependencies = [
        ('osis_document', '0002_increase_maximum_file_name_size'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
