# Generated by Django 3.2.12 on 2022-08-03 16:20

from django.db import migrations, models

from osis_document.models import OsisDocumentFileExtensionValidator


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0003_md5_to_sha256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(max_length=255, upload_to='', validators=[OsisDocumentFileExtensionValidator()], verbose_name='File'),
        ),
    ]
