# Generated by Django 3.2.18 on 2023-03-28 14:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0004_file_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcessing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.CharField(choices=[('MERGE', 'Merge'), ('CONVERT', 'Convert')], max_length=255)),
                ('input_files', models.ManyToManyField(related_name='input_files', to='osis_document.Upload', verbose_name='Input')),
                ('output_files', models.ManyToManyField(related_name='output_files', to='osis_document.Upload', verbose_name='Output')),
            ],
        ),
    ]
