# Generated by Django 3.2.18 on 2023-05-15 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0005_postprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcessAsync',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('DONE', 'Done')], default='PENDING', max_length=255, verbose_name='Status')),
                ('data_post_processing', models.JSONField(default=dict, verbose_name='Data Post Processing')),
                ('input_files', models.ManyToManyField(related_name='input_files_async', to='osis_document.Upload', verbose_name='Input')),
                ('output_files', models.ManyToManyField(related_name='output_files_async', to='osis_document.Upload', verbose_name='Output')),
            ],
        ),
    ]
