# Generated by Django 3.2.18 on 2023-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0006_postprocessasync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprocessasync',
            name='output_files',
        ),
        migrations.AddField(
            model_name='postprocessasync',
            name='post_processing_object',
            field=models.ManyToManyField(related_name='post_processing_object', to='osis_document.PostProcessing', verbose_name='Output'),
        ),
    ]
