# Generated by Django 3.2.18 on 2023-05-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0007_auto_20230515_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprocessasync',
            name='input_files',
        ),
    ]
