# Generated by Django 3.2.18 on 2023-06-01 10:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0011_auto_20230530_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprocessasync',
            name='async_post_processing_progress',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Progress of async post processing'),
        ),
    ]
