# Generated by Django 3.2.21 on 2023-10-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0013_auto_20230601_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='for_modified_upload',
            field=models.BooleanField(blank=True, default=False, verbose_name='For modified upload'),
        ),
        migrations.CreateModel(
            name='ModifiedUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('file', models.FileField(max_length=255, upload_to='', verbose_name='File')),
                ('size', models.IntegerField(verbose_name='Size (in bytes)')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modified_upload', to='osis_document.upload', verbose_name='Upload')),
            ],
        ),
    ]
