# Generated by Django 3.2.20 on 2023-07-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0013_auto_20230601_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostProcessAsync',
            new_name='PostProcessingController',
        ),
    ]
