# Generated by Django 3.2.23 on 2024-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_document', '0015_upload_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('UPLOADED', 'Uploaded'), ('DELETED', 'Deleted'), ('INFECTED', 'Infected')], default='REQUESTED', max_length=255, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token'], name='osis_docume_token_2b8dca_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token', 'expires_at'], name='osis_docume_token_4e389a_idx'),
        ),
    ]
