# Generated by Django 4.2.20 on 2026-02-04 12:10

import django.core.serializers.json
from django.db import migrations, models
import external_storage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(default=uuid.uuid4, max_length=1024, primary_key=True, serialize=False, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(default=external_storage.models.default_expiration_time, verbose_name='Expires at')),
                ('external_storage_name', models.CharField(choices=[('EPC', 'EPC')], verbose_name='External storage name')),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Metadata')),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'external_storage_name'], name='external_st_token_bbba93_idx'), models.Index(fields=['expires_at', 'external_storage_name'], name='external_st_expires_4ebe81_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('created_at'))), name='valid_expiry'),
        ),
    ]
