# Generated by Django 2.2.13 on 2021-05-26 10:41

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None)),
            ],
        ),
    ]
