# Generated by Django 2.2.13 on 2021-05-26 10:41

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osis_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='TestDocument',
            name='other_documents',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1),
        ),
    ]
