# Generated by Django 3.2.18 on 2023-03-28 14:00

from django.db import migrations, models

import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_test', '0002_other_documents_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdocument',
            name='documents',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='testdocument',
            name='other_documents',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
    ]
