# Generated by Django 3.2.21 on 2023-11-13 16:14

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_test', '0003_auto_20230328_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdocument',
            name='documents_expirables',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
    ]
